In [1]:
from funasr_onnx import Fsmn_vad

model_dir = "../FSMN-VAD/"
model = Fsmn_vad(model_dir, quantize=True)

wav_path = "audio_de_test_mono.wav"

result = model(wav_path)
print(result)

/work/dpandya/miniconda3/envs/learning/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/work/dpandya/miniconda3/envs/learning/lib/python3.10/site-packages/funasr_onnx/punc_bin.py:267: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  def vad_mask(self, size, vad_pos, dtype=np.bool):


AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [1]:
import speechbrain
import numpy as np
import matplotlib.pyplot as plt
import os

/work/dpandya/miniconda3/envs/learning/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
torchvision is not available - cannot save figures


In [58]:
import torchaudio
from speechbrain.pretrained import SpeakerRecognition
from speechbrain.pretrained import VAD
#from speechbrain.pretrained import EncoderClassifier

VAD = VAD.from_hparams(source="speechbrain/vad-crdnn-libriparty", savedir='pretrained_models/VAD')
verification = SpeakerRecognition.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", savedir="pretrained_models/spkrec-ecapa-voxceleb")
#classifier = EncoderClassifier.from_hparams('speechbrain/spkrec-ecapa-voxceleb')

In [80]:
def create_chunks_fromPath(path, c_size, stride):
    
    signal, sr = torchaudio.load(path)
    chunks_tensor = VAD.create_chunks(signal, chunk_size=c_size*sr, chunk_stride=stride*sr)
    chunk_dir = path.split('.wav')[0]
    if not os.path.isdir(chunk_dir):
        os.makedirs(chunk_dir)
    #os.mkdir(chunk_dir)
    chunk_fn_list = []
    print(chunks_tensor.shape)
    for i in range(0, chunks_tensor.shape[0]):
        outfn = f'{chunk_dir}/chunk{i}.wav'
        chunk_fn_list.append(outfn)
        torchaudio.save(outfn, chunks_tensor[i].unsqueeze(0), sr)
    
    return chunk_fn_list

audio_wav = '../audioData/familyDecisionVids/336.wav'
#audio_wav = 'audio_de_test_mono.wav'

'''signal, sr = torchaudio.load(audio_wav)
signal.shape, sr'''

'signal, sr = torchaudio.load(audio_wav)\nsignal.shape, sr'

In [81]:
aud_list = create_chunks_fromPath(audio_wav,10,2)

torch.Size([318, 160000])


In [83]:
for i in range(0, len(aud_list)):
    print(VAD.get_speech_segments(aud_list[i]))

tensor([[1.7400, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.6100]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9400]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9000]])
tensor([[0.0000, 7.8900],
        [9.5900, 9.9800]])
tensor([[0.0000, 5.7500],
        [7.7800, 9.9800]])
tensor([[0.6200, 3.6100],
        [5.7200, 9.9800]])
tensor([[0.0000, 2.0900],
        [3.1700, 9.9800]])
tensor([[0.9300, 9.9800]])
tensor([[0.4100, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 9.9800]])
tensor([[0.0000, 8.3600],
      

In [44]:
#segment_list = VAD.get_speech_segments('../audioData/familyDecisionVids/336.wav')
chunks_tensor = VAD.create_chunks(signal, chunk_size=10*sr, chunk_stride=2*sr)

In [51]:
sss = audio_wav.split('.')[0]

for i in range(0, chunks_tensor.shape[1]-1):
    out_fn = f'{sss}_chunk{i}.wav'
    torchaudio.save(out_fn,chunks_tensor[i].unsqueeze(0),16000)
    print(out_fn)

audio_de_test_mono_chunk0.wav
audio_de_test_mono_chunk1.wav
audio_de_test_mono_chunk2.wav
audio_de_test_mono_chunk3.wav
audio_de_test_mono_chunk4.wav
audio_de_test_mono_chunk5.wav
audio_de_test_mono_chunk6.wav
audio_de_test_mono_chunk7.wav
audio_de_test_mono_chunk8.wav
audio_de_test_mono_chunk9.wav
audio_de_test_mono_chunk10.wav
audio_de_test_mono_chunk11.wav
audio_de_test_mono_chunk12.wav
audio_de_test_mono_chunk13.wav
audio_de_test_mono_chunk14.wav
audio_de_test_mono_chunk15.wav
audio_de_test_mono_chunk16.wav
audio_de_test_mono_chunk17.wav
audio_de_test_mono_chunk18.wav
audio_de_test_mono_chunk19.wav
audio_de_test_mono_chunk20.wav
audio_de_test_mono_chunk21.wav
audio_de_test_mono_chunk22.wav
audio_de_test_mono_chunk23.wav
audio_de_test_mono_chunk24.wav
audio_de_test_mono_chunk25.wav
audio_de_test_mono_chunk26.wav
audio_de_test_mono_chunk27.wav
audio_de_test_mono_chunk28.wav
audio_de_test_mono_chunk29.wav


IndexError: index 30 is out of bounds for dimension 0 with size 30

In [89]:
import torch

USE_ONNX = False

model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad',
                              model='silero_vad',
                              force_reload=True,
                              onnx=USE_ONNX)

(get_speech_timestamps,
 save_audio,
 read_audio,
 VADIterator,
 collect_chunks) = utils

Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /home/dpandya/.cache/torch/hub/master.zip


In [90]:
for i in range(0, len(aud_list)):
    wav = read_audio(aud_list[i], sampling_rate=16000)
    speech_timestamps = get_speech_timestamps(wav, model, sampling_rate=16000)
    print(speech_timestamps)
    print(i)

[{'start': 38944, 'end': 49632}, {'start': 55328, 'end': 91616}, {'start': 99872, 'end': 139232}, {'start': 143392, 'end': 160000}]
0


KeyboardInterrupt: 

In [88]:
wav = read_audio('audio_de_test_mono.wav', sampling_rate=16000)
# get speech timestamps from full audio file
speech_timestamps = get_speech_timestamps(wav, model, sampling_rate=16000)
print(speech_timestamps)

KeyboardInterrupt: 

In [52]:
segment_list = VAD.get_speech_segments('/work/dpandya/giggityGit/SpeakerDiarization/audio_de_test_mono_chunk0.wav')

In [53]:
segment_list

tensor([[2.8700, 9.9800]])

In [ ]:

embeddings = classifier.encode_batch(signal)